# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8259bb1ca428d7cab88979e5d437cce58801eb6b5b14d619375a1d0d13b906f67c6e50cf182011667b167ab1d08103a709094de45c53ecc89ac4125afe3f17dc

test:
  secret_key_base: ed8931b8049c361dfaae003698ea60ecc67370521c03ab38a0589a2be0ad2683d6ae911511cce459dbf8d1291abc4324e933ebda56a20971230efd753118be4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
